# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1064-0A0A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
